# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058014a37df28a7243be0878b93819eff6c9cd2fa675e55dc03527c1b1af2d7438275851f25ab6a46f85ca4bd1c3949df15c2154182298418c8825769f734135

test:
  secret_key_base: 94829248c1461c3c214c8ee238ed8bbbd6431ef4718ef1fc87304491d09b8eae11dbedaf1b0b08a2372dade4e7fb5e6baf00f685803e352c20d6646fba3665a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
